### ISSUE TITLE
dependencies in `pyproject.toml`

### ISSUE THREAD

**Issue by elmiraloo** [YiyangZhou/POVID#1]
Hi, I'm trying to reproduce the results in the paper and I've noticed a possible issue with the dependencies. e.g. There's an error caused by [this  line](https://github.com/YiyangZhou/POVID/blob/d94736b72a518596e1aa360de114bdb9c75c9bf8/llava/train/llava_trainer.py#L12), which seems to be [a known issue ](https://github.com/haotian-liu/LLaVA/issues/1042) related to `transformers==4.37.2` in the dependencies (it's fixed in the original LLaVA codebase ). That one is easy to fix. But there might be some other version mismatch problems, causing the following error. Can you confirm if everything is working on your side following the instructions in the readme.

```
assert self.params_already_reduced[param_id] == False, \
AssertionError: The parameter 447 has already been reduced.
```

**Comment by elmiraloo** [comment]
ok here are the fixes needed to run the code 
1. `b/llava/train/llava_trainer.py` should be replaced by the same file from the main llava repository.
2. in `llava/train/train_dpo.py`` mm_patch_merge_type: Optional[str] = field(default='flat')` is missing in model arguments.
3. `gradient_checkpointing_kwargs={"use_reentrant":False}` needs to be passed to dpo trainer to avoid the above error.

**Comment by si0wang** [comment]
Hi, I encountered the same issue, could please tell me where should I put gradient_checkpointing_kwargs={"use_reentrant":False}? Is it dpo_trainer.py or train_dpo.py? I have tried both and neither works for me.

**Comment by elmiraloo** [comment]
I actually overwrote it in `torch/utils/checkpoint.py ` The default based on the comments on the code will be False in future anyways

**Comment by elmiraloo** [comment]
Fixed after the fixes suggested above.
