### ISSUE TITLE
Result for Pope not reproduced [Issue]

### ISSUE THREAD

**Issue by rohan598** [YiyangZhou/POVID#2]
First of all great work @YiyangZhou and team! I have been trying to reproduce the hallucination score on POPE. I have merged the second checkpoint weights you have hosted on HF with base llava-v1.5-7b parameter model to get the final model. 

This model gives me **86.01** and not _86.90_ 

Note: Using the pope eval script given in your repo (based on llava eval), I am able to reproduce LLava-v1.5-7b base model result of **85.9**

I suspect an issue in the right way of merging weights across stage 1 and stage 2. would love to hear more from you

**Comment by elmiraloo** [comment]
I think you should merge llava-1.5 with stage one first and then that one with stage two.
