### ISSUE TITLE
Visualize Attention Map

### ISSUE THREAD

**Issue by franciscoliu** [YiyangZhou/POVID#4]
Dear authors,

Wonderful works! Wondering if you could kindly offer the code to visualize Figure 5 in your paper.

**Comment by tangli-udel** [comment]
Could you point me to where I can find the code for generating Figure 5? Thanks!

**Comment by benllame** [comment]
Were you able to do it? I'm interested in it too

**Comment by franciscoliu** [comment]
Yes, I ended up writing a script myself, but I didn't reproduce the exact same attention maps as the paper.
